# fly.toml app configuration file generated for 1q1a-server on 2024-10-04T11:55:48+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '1q1a-server'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
